<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_My_Personal_Information</name>
   <tag></tag>
   <elementGuidId>fef26ad1-74c7-41f1-b789-071516b0930b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;myaccount-link-list&quot;]//*[@href=&quot;http://automationpractice.com/index.php?controller=identity&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
